#
# http://deeeet.com/writing/2014/10/02/docker-private-registry-auth/
#

version: '2'

#volumes:
#  vol-data:
#    external: false

services:

  rproxy:
    build:
      context: .
      dockerfile: Dockerfile.rproxy
    image: rproxy
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro

  my-docker-hub:
    image: registry
    environment:
      - STORAGE_PATH=/registry
      - VIRTUAL_HOST=my-docker-hub
    expose:
      - "5000"
    volumes:
      - ./data:/registry

  test:
    image: ubuntu
